### ISSUE TITLE
Need a page for badges/resume page

### ISSUE THREAD

**Issue by GrillinFool** [jasonbutler42/grillinfools#16]
Need some sort of resume with the badges I've earned:

Farmland Bacon
Char-Broil
Kraft
Epicurious
Culinary Content Network

As well as these brands:

Sears
Kraftig
Grill Dome
Rockwood Charcoal
Maybe Arby's
Royal Caribbean
Flat Out Pizza Bread
JK Adams Cutting Boards
Saber Grills
Fix.com

**Comment by jasonbutler42** [comment]
From #46: 

I believe the best place for the brands we've worked with is on the "Advertise" page. All we have there is some text and a couple links there. Let's spice that up with some badges and such.

**Comment by jasonbutler42** [comment]
Some of these will need to be resized and have background colors, but this looks like everything.
![arbys](https://cloud.githubusercontent.com/assets/1919724/6131817/553b9e8e-b114-11e4-85ed-6c87b1859827.jpg)
![ccnsprite](https://cloud.githubusercontent.com/assets/1919724/6131820/553bf154-b114-11e4-9563-38253fb82e48.png)
![epicurious](https://cloud.githubusercontent.com/assets/1919724/6131818/553bcda0-b114-11e4-9183-ad306814d8d0.png)
![farmland](https://cloud.githubusercontent.com/assets/1919724/6131821/553bf7d0-b114-11e4-815c-1e1919df411a.png)
![fix com](https://cloud.githubusercontent.com/assets/1919724/6131822/553c02fc-b114-11e4-9c67-1e956083994a.png)
![flatout-flatbread-logo](https://cloud.githubusercontent.com/assets/1919724/6131819/553bd854-b114-11e4-9f36-8b1220bd7d17.jpg)
![grilldome](https://cloud.githubusercontent.com/assets/1919724/6131823/554635ba-b114-11e4-8896-e9415977ca2f.jpg)
![jkadams](https://cloud.githubusercontent.com/assets/1919724/6131824/5547185e-b114-11e4-95fb-78db876c5767.png)
![kraft_foods_logo2012](https://cloud.githubusercontent.com/assets/1919724/6131828/55483158-b114-11e4-8ecc-76bd47fc56be.png)
![kraftig-william-k-busch-logo-200x200](https://cloud.githubusercontent.com/assets/1919724/6131826/5547a2d8-b114-11e4-9641-b4733d7264f9.png)
![new_hr_char-broil logo 1_27721](https://cloud.githubusercontent.com/assets/1919724/6131825/55476c32-b114-11e4-9ef5-455a16f4849d.jpg)
![rockwood-logo-home](https://cloud.githubusercontent.com/assets/1919724/6131827/5548337e-b114-11e4-85a3-8d3850c9a4a7.png)
![royal-caribbean](https://cloud.githubusercontent.com/assets/1919724/6131830/555297ec-b114-11e4-8458-2ec904cb9229.png)
![saber](https://cloud.githubusercontent.com/assets/1919724/6131829/5551d6cc-b114-11e4-88ed-494a098ed5a8.png)

**Comment by GrillinFool** [comment]
That looks like all of them although I feel like we're missing one but can't figure out which one. 
One thing. What did we do with epicurious?
--
Sent from myMail app for Android
Tuesday, 10 February 2015, 11:03AM -06:00 from jasonbutler42 <notifications@github.com>:
Some of these will need to be resized and have background colors, but this looks like everything.

**Comment by jasonbutler42** [comment]
No idea, I just grabbed logos for the places you listed.

**Comment by GrillinFool** [comment]
Skip epicurious. Can't think of what we did with them.
 
 
 
--------- Original Message --------- Subject: Re: [grillinfools] Need a page for badges/resume page (#16)

**Comment by GrillinFool** [comment]
I remember the other name. Sears. 
--------- Original Message --------- Subject: Re: [grillinfools] Need a page for badges/resume page (#16)
