### ISSUE TITLE
A lot of white space below the recipe box

### ISSUE THREAD

**Issue by GrillinFool** [jasonbutler42/grillinfools#42]
Can we move the related posts up in there and above the author bio deal?
![screen shot 2014-12-30 at 4 20 10 pm](https://cloud.githubusercontent.com/assets/10049609/5583522/fd1a6ab8-903f-11e4-9035-61eba372defb.png)

**Comment by jasonbutler42** [comment]
This is happening on a post-by-post basis because there's a bunch of extra paragraphs after teh recipe box. If you look at the editing page under text view, you'll see a bunch of:
```
&nbsp;

&nbsp;
```
Take those out and the extra space will go away.
