### ISSUE TITLE
Ad order on the main page

### ISSUE THREAD

**Issue by GrillinFool** [jasonbutler42/grillinfools#46]
We need to adjust these. I need them in this order:

Andria's
Kraftig
Grill Dome
Circle B Ranch
Mateker's
Rockwood
Code 3

Remove Farmland Bacon. That campaign is done. But we need to add that badge to a "Brands we've worked with page" 

I believe the best place for the brands we've worked with is on the "Advertise" page. All we have there is some text and a couple links there. Let's spice that up with some badges and such.

**Comment by jasonbutler42** [comment]
The order has been changed and Farmland has been removed. Making a note on #16 about putting the badge on the advertise page.
