### ISSUE TITLE
Need a solution for a sort of directory of meat markets/butchers and bars and such

### ISSUE THREAD

**Issue by GrillinFool** [jasonbutler42/grillinfools#54]
Once dad is back from vacation, I'm going to sick he and Tom on the local butchers and bars. We want to do a cost effective way to advertise. Say $50-75/month for one advertiser that rotates between a bunch of advertisers of the same class. Basically we need to structure some different advertising rates.

**Comment by jasonbutler42** [comment]
Our current advertising option in the sidebar on desktop can handle this very easily. We can create a new block that rotates. The rotation is random but can be weighted so that if soemone pays more, their ad shows up more often.

**Comment by GrillinFool** [comment]
Weighting is good. Although to start, we'll leave it even for everyone. 
 
The next thing I want is that the ads link to a sort of directory. I want something that has a paragraph or two about the place, one picture and a small map of their location. When someone clicks on the ad, it takes them the user to the specific synopsis they clicked out of the list. Does that make sense?
 
--------- Original Message --------- Subject: Re: [grillinfools] Need a solution for a sort of directory of meat markets/butchers and bars and such (#54)
