### ISSUE TITLE
Need Older Posts button to keep on going

### ISSUE THREAD

**Issue by GrillinFool** [jasonbutler42/grillinfools#55]
On my laptop, I can scroll to the bottom and hit older posts but then if I scroll to the bottom of those posts, there is no more chance to click for older posts after that. I need that button to keep reappearing until there are no posts left.

**Comment by GrillinFool** [comment]
Same for mobile.

**Comment by jasonbutler42** [comment]
I was having some trouble with weird 404s caused by the default behavior, so I made it a manual click. The 404's don't really cause any problems other than going into the logs. I turned the default behaviour back on, so now it should scroll infinitely, or until you run out of posts.
