### ISSUE TITLE
Broken Char-Broil links

### ISSUE THREAD

**Issue by jasonbutler42** [jasonbutler42/grillinfools#57]
The following Char-Broil links recently broke:

- http://www.charbroil.com/grills/gas-grills/gourmet-tru-infrared-series/char-broil-gourmet-t-47d.html?utm_source=scott-thomas-web&utm_medium=article-link&utm_campaign=all-star-blogger
- http://www.charbroil.com/smokers-fryers/the-big-easy-oil-less-turkey-fryer-14101480.html?utm_source=scott-thomas-web&utm_medium=article-link&utm_campaign=all-star-blogger
- http://www.charbroil.com/the-big-easyr-2-in-1-electric-smoker-roaster-11101625-a1.html

Looks like they restructured their site. I can find links to the equivalent products, but I don't know if or how your affiliate links work.

**Comment by GrillinFool** [comment]
The link simply has to have this at the end:
 
?utm_source=scott-thomas-web&utm_medium=article-link&utm_campaign=all-star-blogger
 
--------- Original Message --------- Subject: [grillinfools] Broken Char-Broil links (#57)

**Comment by jasonbutler42** [comment]
Fixed
